
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 21 18:30:36 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 7;
  public static final int For = 10;
  public static final int Operadoresbooleano = 20;
  public static final int Suma = 12;
  public static final int Numero = 30;
  public static final int CorchetesAbierto = 25;
  public static final int ParentesisAbierto = 21;
  public static final int ERROR = 31;
  public static final int TipoDato = 4;
  public static final int Identificador = 29;
  public static final int LlavesAbierto = 23;
  public static final int Comillas = 3;
  public static final int LLavesCerrado = 24;
  public static final int Operadoresrelacional = 17;
  public static final int Main = 27;
  public static final int CorchetesCerrado = 26;
  public static final int Cadena = 5;
  public static final int ParentesisCerrado = 22;
  public static final int EOF = 0;
  public static final int Division = 15;
  public static final int OperadoresLogico = 16;
  public static final int Operadoresincremento = 19;
  public static final int Operadoresatribucion = 18;
  public static final int Resta = 13;
  public static final int If = 6;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Do = 8;
  public static final int Igual = 11;
  public static final int While = 9;
  public static final int Multiplicacion = 14;
  public static final int PuntoComa = 28;
}

